name = "mfe-shell"
compatibility_date = "2026-01-22"
workers_dev = false

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "mfe-shell.marek.work"
custom_domain = true
